SELECT NAME FROM EMPLOYEE;
SELECT NAME FROM EMPLOYEE ORDER BY DATE_OF_BIRTH;
SELECT NAME FROM EMPLOYEE ORDER BY NAME;
SELECT NAME FROM CUSTOMER;
SELECT c.NAME, e.NAME FROM CUSTOMER c, EMPLOYEE e WHERE e.ID = c.EMPLOYEE_ID;
SELECT c.NAME, e.NAME FROM EMPLOYEE e INNER JOIN CUSTOMER c ON (e.ID = c.EMPLOYEE_ID);
--Exemple left join
SELECT c.NAME, e.NAME FROM EMPLOYEE e LEFT JOIN CUSTOMER c ON (e.ID = c.EMPLOYEE_ID);
--Exemple left join al where (+) = left join
SELECT c.NAME, e.NAME FROM CUSTOMER c, EMPLOYEE e WHERE e.ID = c.EMPLOYEE_ID(+);