UPDATE EMPLOYEE SET SURNAME='Treballador 1' WHERE NAME='Treballador 1';
UPDATE EMPLOYEE SET SURNAME='Treballador 2' WHERE NAME='Treballador 2';
UPDATE EMPLOYEE SET SURNAME='Treballador 3' WHERE NAME='Treballador 3';

UPDATE CUSTOMER SET SURNAME='Client 1.1' WHERE NAME='Client 1.1';
UPDATE CUSTOMER SET SURNAME='Client 1.2' WHERE NAME='Client 1.2';
UPDATE CUSTOMER SET SURNAME='Client 1.3' WHERE NAME='Client 1.3';
UPDATE CUSTOMER SET SURNAME='Client 2.1' WHERE NAME='Client 2.1';
UPDATE CUSTOMER SET SURNAME='Client 2.2' WHERE NAME='Client 2.2';
UPDATE CUSTOMER SET SURNAME='Client 2.3' WHERE NAME='Client 2.3';

UPDATE CUSTOMER SET SURNAME='Client' || SEQ_CUSTOMER.NEXTVAL;

SELECT * FROM CUSTOMER;

