DROP SEQUENCE SEQ_ID;
DROP SEQUENCE SEQ_NAME;
DROP SEQUENCE SEQ_DESC;

CREATE SEQUENCE SEQ_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NAME START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DESC START WITH 1 INCREMENT BY 1;

INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);
INSERT INTO PRODUCT VALUES (SEQ_ID.NEXTVAL, 'PRODUCTE ' || SEQ_NAME.NEXTVAL, 'PRODUCTE ' || SEQ_DESC.NEXTVAL);

--(TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss')

INSERT INTO PRODUCT_CUSTOMER VALUES (1, 1, TO_DATE('2003/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (3, 5, TO_DATE('2005/02/19 06:48:24', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (4, 7, TO_DATE('2010/05/01 12:20:35', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (9, 5, TO_DATE('2013/11/30 10:22:17', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (7, 2, TO_DATE('2009/08/14 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (2, 3, TO_DATE('2014/10/23 23:04:58', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (6, 6, TO_DATE('2006/01/21 15:30:21', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (8, 1, TO_DATE('2002/09/13 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (3, 7, TO_DATE('2015/06/26 22:30:19', 'yyyy/mm/dd hh24:mi:ss'));
INSERT INTO PRODUCT_CUSTOMER VALUES (5, 4, TO_DATE('2008/03/05 09:04:20', 'yyyy/mm/dd hh24:mi:ss'));

DELETE FROM PRODUCT;
DELETE FROM PRODUCT_CUSTOMER;

COMMIT;