INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'nombre', 'descripcion');

DROP SEQUENCE SEQ_PRODUCT;

CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1 MAXVALUE 3;

INSERT INTO PRODUCT VALUES (SEQ_PRODUCT.NEXTVAL, 'nombre', 'descripcion');